language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - nightly

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml --configuration build/phpunit.xml

after_success:
  - php vendor/bin/coveralls -v
