language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mkdir -p build/logs

script:
  - phpunit --configuration build/phpunit.xml

after_success:
  - php vendor/bin/coveralls -v
